kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-{{  template "name" . }}-client-provisioner
subjects:
- kind: ServiceAccount
  name: {{  template "name" . }}-client-provisioner
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{  template "name" . }}-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io