apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  template "name" . }}-client-provisioner
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{  template "name" . }}-client-provisioner
  template:
    metadata:
      labels:
        app: {{  template "name" . }}-client-provisioner
    spec:
      serviceAccountName: {{  template "name" . }}-client-provisioner
      containers:
      - name: {{  template "name" . }}-client-provisioner
        image: quay.io/external_storage/nfs-client-provisioner:latest
        volumeMounts:
        - name: {{  template "name" . }}-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: efs-storage
        - name: NFS_SERVER
          value: {{ .Values.nfs_server }}
        - name: NFS_PATH
          value: {{ .Values.nfs_path }}
      volumes:
      - name: {{  template "name" . }}-client-root
        nfs:
          server: {{ .Values.nfs_server }}
          path: {{ .Values.nfs_path }}