kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-{{  template "name" . }}-client-provisioner
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]