kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: leader-locking-{{  template "name" . }}-client-provisioner
subjects:
- kind: ServiceAccount
  name: {{  template "name" . }}-client-provisioner
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{  template "name" . }}-client-provisioner
  apiGroup: rbac.authorization.k8s.io