apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "airflow.fullname" . }}-redis
type: Opaque
data:
  redis-password: "YWlyZmxvdw=="