{{- with index .Values "cluster-configs" "secrets" "airflow" }}
{{- if index . "db_user" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  db_user: {{ toYaml (index . "db_user") | b64enc | quote }}
  db_password: {{ toYaml (index . "db_password") | b64enc | quote }}
{{- end }}
{{- end }}