
{{- with index .Values "cluster-configs" "secrets" "egov-filestore-azure" }}
{{- if index . "account-key" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  accountName: {{ index . "account-name" | b64enc | quote }}
  accountKey: {{ index . "account-key"  | b64enc | quote }}
{{- end }}
{{- end }}